spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/quiz;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false


logging:
  level:
    org.hibernate.sql: info
    #org.hibernate.type: trace
    root: info

security:
  access-token:
    secret-key: abcdefghijklmnopqrstuvwxyz0123456789
    life-time: 86400000
  refresh-token:
    life-time: 86400000
